### ISSUE TITLE
Find out why our builds are so much faster

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/tools-team#7]
We had a report from a user on slack of builds going from 2 minutes to 17 seconds.

This is old Hydrolysis + Vulcanize vs Analyzer + Bundler, so we'd hope for some improvements, but it'd be nice to document and verify.

**Comment by web-padawan** [comment]
Actually, the project I'm working on has 52 fragments in `polymer.json` file, although some of them are quite small (e. g. "callback" pages for some API requests). 

Looks like running `vulcanize` for such number of fragments was a pain, because build required more than 2560 M memory limit, as specified [here](https://github.com/Polymer/polymer-bundler/issues/394). 

Having such limit configured via `node --max-old-space-size=3072`, we were still limited by memory allowed to use by Docker (2048 by default for most of our team, as well as in our CI). So, as I suppose, in fact builds were using swap after exceeding that limit. 

After upgrading to `polymer-bundler`, on my Mac mini (no SSD) it only takes 38-42 sec, and in CI it takes 17-20 sec. Both running in Docker, using `docker-node` 6.9.4.

**Comment by usergenic** [comment]
This issue is sort of obviated by time, so I'm closing it.

**Comment by web-padawan** [comment]
Anyway, our project has grown since that time and our builds are not fast anymore :disappointed: 
Especially bundler runs 1 min, but that's pretty much understandable due to components count increase.

**Comment by usergenic** [comment]
_wow_
